### ISSUE TITLE
ketchup: command not found

### ISSUE THREAD

**Issue by hoang17** [ketchuphq/ketchup#1]
i tried to run ketchup on mac os but get this error

```
Hoangs-MacBook-Pro-2:ketchup_Darwin_x86_64 hoangle$ ketchup users:add myemail@gmail.com
-bash: ketchup: command not found

```

**Comment by lillesvin** [comment]
Unless you've downloaded the binary and put it somewhere in your PATH, then you'll be seeing that. Try `./ketchup ...` instead (with './' in front of 'ketchup') to indicate that Bash should look for it in the current directory rather than in PATH.

**Comment by hoang17** [comment]
thanks its working now but there seems to be no default theme, after i created a page it showed only content without any layout

**Comment by octavore** [comment]
@lillesvin Thanks, that's exactly right! 

@hoang17 To answer your second question, that is the default theme you're seeing, which unfortunately is not much to look at right now.
