### ISSUE TITLE
Nothing is showing on the page with compose

### ISSUE THREAD

**Issue by habuka036** [ketchuphq/ketchup#13]
Hi

ketchup v0.3.0 not rendering correctly in compose page as following:

![image](https://user-images.githubusercontent.com/369315/40795368-d42e3118-653c-11e8-80ff-60c5f194d361.png)

The HTML source at this time as follows:

```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Ketchup</title>
  <link rel="icon" type="image/png" href="/admin/images/k_32.png">
  <script src="/admin/js/vendor.js"></script>
  <script src="/admin/js/app.js"></script>

  <link href="https://cdnjs.cloudflare.com/ajax/libs/typicons/2.0.8/typicons.min.css" rel="stylesheet" media="none" onload="if(media!='all')media='all'" />
  <link rel="stylesheet" href="/admin/vendor/quill.snow.css" />
  <link rel="stylesheet" href="/admin/vendor/codemirror.css" />
  <link rel="stylesheet" href="/admin/vendor/elegant.css" />
  <link rel="stylesheet" href="/admin/css/app.css" />
</head>

<body>
  <div id="react-root"></div>
</body>

</html>
```

Could you please confirm this?

Thank you.

**Comment by octavore** [comment]
Thanks! This is now fixed on master (and will be in v0.3.1 to be released soon), there was an ordering bug with triggering the new page in the backing store before subscribing to the store events. This caused the page to not perform the initial render.
