### ISSUE TITLE
Index page not found

### ISSUE THREAD

**Issue by maxtar** [ketchuphq/ketchup#4]
I've do all steps from [Quick start page](https://ketchuphq.com/docs). And noted two mistakes:
1. Incorrect port. On page mentioned 8080, but real port is 8000.
2. url http://localhost:8080 return 404 error. And I doesn't see login page where I can input created user.

**Comment by octavore** [comment]
Thanks for the feedback! I've fixed the docs to refer to the correct port 8000, and also amended the URL to the login page, which should be at `http://localhost:8000/admin`.

**Comment by maxtar** [comment]
Thanx! It's works! :)
